openapi: 3.2.0
info:
  title: Payment Gateway
  version: v1
  x-service-name: payment-gateway
  x-codegen-settings:
    java:
      packageName: org.hamsaqua.payment.authorize.openapi.v1.gateway
    kotlin:
      packageName: org.hamsaqua.payment.authorize.openapi.v1.gateway
  description: |
    - Public endpoint for merchants to initiate authorization requests.
    - Immediate ACK returned; final result delivered via webhook/callback or via event.
servers:
  - url: https://gateway.internal
paths:
  /v1/authorize:
    post:
      summary: Initiate payment authorization
      operationId: authorizePayment
      tags: [ authorize ]
      parameters:
        - name: X-Correlation-Id
          in: header
          schema:
            type: string
            format: uuid
          description: Correlation id; if absent server will generate one.
        - name: Idempotency-Key
          in: header
          schema:
            type: string
          description: Client-provided idempotency key to deduplicate inbound requests.
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizeRequestV1'
      responses:
        '200':
          description: Acknowledgement returned to merchant
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuthorizeAckV1'
        '400': { description: Invalid input }
        '401': { description: Unauthorized }
        '500': { description: Server error }
components:
  schemas:
    AuthorizeRequestV1:
      type: object
      properties:
        transactionId:
          type: string
          format: uuid
          description: Optional, gateway generates if absent.
        merchantId: { type: string }
        payerId: { type: string }
        orderId: { type: string }
        amount: { type: number }
        currency: { type: string }
        card:
          type: object
          properties:
            token: { type: string }
            maskedPan: { type: string }
          required: [ token, maskedPan ]
        timestamp:
          type: string
          format: date-time
        correlationId:
          type: string
          format: uuid
      required: [ merchantId, payerId, orderId, amount, currency, card ]
    AuthorizeAckV1:
      type: object
      properties:
        correlationId: { type: string, format: uuid }
        transactionId: { type: string, format: uuid }
        status:
          type: string
          enum: [ ACCEPTED, REJECTED, ERROR_PUBLISH ]
        timestamp: { type: string, format: date-time }
      required: [ correlationId, transactionId, status, timestamp ]
security: [ ]
