openapi: 3.2.0
info:
  title: Shopping Merchant
  version: v1
  description: |
    Merchant-facing APIs for initiating and handling payment authorization flows.
    This specification covers:
    - Public endpoint (called by payer-facing app)
    - Webhook endpoint (called by payment gateway)
servers:
  - url: https://merchant.internal
paths:
  /v1/checkout/pay:
    post:
      summary: Initiate checkout payment
      description: |
        Endpoint called by payer-facing frontend/app to initiate a payment.
        Merchant system will internally call the Payment Gateway API `/v1/authorize`
        and return an immediate acknowledgement to the payer.
      operationId: initiateCheckoutPayment
      tags: [ checkout ]
      parameters:
        - name: X-Correlation-Id
          in: header
          schema:
            type: string
            format: uuid
          description: Correlation id for tracing (optional; generated if missing)
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CheckoutPaymentRequestV1'
      responses:
        '200':
          description: Payment request accepted
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CheckoutPaymentAckV1'
        '400': { description: Invalid input }
        '500': { description: Internal server error }
  /v1/webhooks/payment/authorize-result:
    post:
      summary: Receive payment authorization result from Gateway
      description: |
        Webhook endpoint that receives final authorization result from Payment Gateway.
        This endpoint must be idempotent and secured with shared secret or signature.
      operationId: handleAuthorizeResult
      tags: [ webhook ]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AuthorizeResultCallbackV1'
      responses:
        '200':
          description: Acknowledged
        '400': { description: Invalid payload }
        '401': { description: Unauthorized }
        '500': { description: Internal error }
components:
  schemas:
    CheckoutPaymentRequestV1:
      type: object
      description: Payment request initiated by the payer
      properties:
        merchantId: { type: string }
        payerId: { type: string }
        orderId: { type: string }
        amount: { type: number }
        currency: { type: string }
        paymentMethod:
          type: string
          enum: [ CARD, WALLET, BANK_TRANSFER ]
        card:
          type: object
          properties:
            number: { type: string, description: Masked PAN or tokenized form }
            expiry: { type: string }
            cvv: { type: string }
          required: [ number, expiry ]
        timestamp: { type: string, format: date-time }
        correlationId: { type: string, format: uuid }
      required: [ merchantId, payerId, orderId, amount, currency, paymentMethod ]
    CheckoutPaymentAckV1:
      type: object
      description: Immediate acknowledgement returned to payer
      properties:
        correlationId: { type: string, format: uuid }
        orderId: { type: string }
        transactionId: { type: string, format: uuid }
        status:
          type: string
          enum: [ ACCEPTED, REJECTED, PENDING ]
        timestamp: { type: string, format: date-time }
      required: [ correlationId, orderId, status, timestamp ]
    AuthorizeResultCallbackV1:
      type: object
      description: Final authorization result delivered by Gateway
      properties:
        correlationId: { type: string, format: uuid }
        transactionId: { type: string, format: uuid }
        orderId: { type: string }
        merchantId: { type: string }
        status:
          type: string
          enum: [ AUTHORIZED, DECLINED, ERROR ]
        message: { type: string }
        timestamp: { type: string, format: date-time }
      required: [ correlationId, transactionId, orderId, merchantId, status, timestamp ]
security: [ ]
